src/objects/Chat_Message__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Room__c</fullName>
        <label>Chat Room</label>
        <referenceTo>Chat_Room__c</referenceTo>
        <relationshipLabel>Chat Messages</relationshipLabel>
        <relationshipName>Chat_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>CMSG-{0000000000}</displayFormat>
        <label>Chat Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chat_Room__c.object
<CustomObject>
    <label>Chat Room</label>
    <nameField>
        <displayFormat>CRM-{000000000}</displayFormat>
        <label>Chat Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chat_User_Presence__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Room__c</fullName>
        <label>Chat Room</label>
        <referenceTo>Chat_Room__c</referenceTo>
        <relationshipLabel>Chat Users Presence</relationshipLabel>
        <relationshipName>Chat_Users_Presence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chat User Presence</label>
    <nameField>
        <displayFormat>CUP-{000000}</displayFormat>
        <label>Chat User Presence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Users Presence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TEST_Chat_CtrSendMessage.cls
/**
 * Created by mzeuli on 01.11.18.
 */

@IsTest
private class TEST_Chat_CtrSendMessage {
    @IsTest
    static void insertNewMessageReturnsFalseIfTextOrRoomIdAreBlank() {
        Boolean res;

        Test.startTest();

        res = Chat_CtrSendMessage.insertNewMessage('', 'a non blank id');
        res |= Chat_CtrSendMessage.insertNewMessage('a non blank message', '');
        res |= Chat_CtrSendMessage.insertNewMessage('', '');

        Test.stopTest();

        System.assert(!res);
    }

    @IsTest static void insertNewMessageCatchesExceptionAndReturnsFalse() {
        Boolean res;

        Test.startTest();

        DummyChatServiceThatThrowsExcept stub = new DummyChatServiceThatThrowsExcept();

        Chat_CtrSendMessage.chatService = stub;

        res = Chat_CtrSendMessage.insertNewMessage('non blank text', 'fake room id');

        Test.stopTest();

        System.assert(!res);
    }

    @IsTest static void insertNewMessageCallsCorrectServiceMethodAndReturnsTrue() {
        Boolean res, called;

        Test.startTest();

        DummyChatServiceThatInserts stub = new DummyChatServiceThatInserts();

        Chat_CtrSendMessage.chatService = stub;

        res = Chat_CtrSendMessage.insertNewMessage('non blank text', ' a room id');

        called = stub.saveNewMessageCalled;

        Test.stopTest();

        System.assert(res);
        System.assert(called);
    }

    public class DummyChatServiceThatInserts implements IChat_Utils {

        public Boolean saveNewMessageCalled {get; private set;}

        public Chat_Message__c getMessageById(String id) {
            return null;
        }

        public List<Chat_Message__c> getMessages(String roomId, Integer limitSize, Integer offset) {
            return null;
        }

        public Chat_Room__c getOrCreateChatRoomPerRecordId(String recordId) {
            return null;
        }

        public void saveNewMessage(String text, String roomId) {
            saveNewMessageCalled = true;
        }

        public void refreshUserPresence(String roomId) {
        }

        public List<Chat_User_Presence__c> getUsersPresenceByChatRoomId(String roomId) {
            return null;
        }

    }

    public class DummyChatServiceThatThrowsExcept implements IChat_Utils {
        public Chat_Message__c getMessageById(String id) {
            return null;
        }

        public List<Chat_Message__c> getMessages(String roomId, Integer limitSize, Integer offset) {
            return null;
        }

        public Chat_Room__c getOrCreateChatRoomPerRecordId(String recordId) {
            return null;
        }

        public void saveNewMessage(String text, String roomId) {
            throw new DummyException();
        }

        public void refreshUserPresence(String roomId) {
        }

        public List<Chat_User_Presence__c> getUsersPresenceByChatRoomId(String roomId) {
            return null;
        }

    }

    public class DummyException extends Exception {}
}